### PR TITLE
Update ingest tutorial

### PR DESCRIPTION
**Pull request by flying-sheep**

### CODE REVIEW

**Comment by flying-sheep** [comment]
<p>thanks, I saw that some numbers changed but totally missed that one cell type vanished!</p>

---

 <a href='https://app.reviewnb.com/scverse/scanpy-tutorials/pull/139/discussion/#comment-2411335541'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by flying-sheep** [comment]
<p>I checked and nope, they stay the same, as they are manually assigned.</p><p> </p><p>Seems like <code>ingest</code> doesn’t transfer the cell type in batch “2” anymore.</p><p> </p><p>The only thing that changed in the notebook is using <code>anndata.concat</code> instead of <code>anndata.AnnData.concatenate</code>, but that’s not it.</p>

---

 <a href='https://app.reviewnb.com/scverse/scanpy-tutorials/pull/139/discussion/#comment-2411335518'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ilan-gold** [comment]
> Seems like ingest doesn’t transfer the cell type in batch “2” anymore.

Do we want to figure out why or no?

**Comment by ilan-gold** [comment]
> chance

If it's this we should probably set seeds then?

**Comment by flying-sheep** [comment]
I think we should either figure out how to reliably capture that cell type or decide we don’t care. I think that if setting a seed qualitatively changes the result doesn’t count as “reliable”

Maybe “almost completely not captured” vs “completely not captured” is a sign that capturing this cell type isn’t stable

**Comment by ilan-gold** [comment]
> Maybe “almost completely not captured” vs “completely not captured” is a sign that capturing this cell type isn’t stable, but maybe there’s a way to improve the amount of reliably identified mast cells.

I would definitely agree with this sentiment.  Not sure what to do about this PR specifically.  I leave it up to you.  I would say if "nothing" is the answer, maybe we could put a warning in the notebook about small cell clusters.  Really not sure, though.  I went through this issue with the `leiden` upgrade and eventually either landed on "let the change through because there's nothing we can do" or "found some dependency issue"

**Comment by flying-sheep** [comment]
Maybe we can wait for @Koncopd to come back from holiday and get a comment, I think he wrote the ingest code originally.

**Comment by ilan-gold** [comment]
@flying-sheep Sounds good to me

**Comment by flying-sheep** [comment]
@Koncopd could you please take a look?

**Comment by flying-sheep** [comment]
apparently not

**Review by ilan-gold — APPROVED** [review]

**Pull request merged**
