### PR TITLE
Revert "(chore): use `read_elem_as_dask`"

### PR DESCRIPTION
**Pull request by ilan-gold**
Reverts scverse/scanpy-tutorials#124

### CODE REVIEW

**Comment by ilan-gold** [comment]
@flying-sheep I should not have merge the other PR, too quick.

**Comment by ilan-gold** [comment]
And I don't have rights here to merge this myself

**Comment by flying-sheep** [comment]
It’s fine, scanpy’s docs only update when we update the submodule in the scanpy repo, so it already being updated here is OK

**Comment by flying-sheep** [comment]
I reopened https://github.com/scverse/anndata/issues/1133, we can do a PR to scanpy that updates the submodule and closes that issue

**Pull request closed without merging**
