### PR TITLE
Update Marsilea example notebook

### PR DESCRIPTION
**Pull request by Mr-Milk**
- Given the API updates from `hsplit/vsplit` -> `group_rows/group_cols` in Marsilea, @ivirshup has updated the API usage. I then updated the text description.
- Add an example for tracksplot (With marsilea >= 0.3.4).
- Add an example for stacked violin plot.

### CODE REVIEW

**Review by flying-sheep — COMMENTED** [review]
Looks nice, I just see a typo:

> Futhrer plots, like stacked violin

**Comment by ivirshup** [comment]
image

Any chance this could be a little nicer? I think a rotation of the label could be more readable.

This is getting a little fancier, but could you also remove the updates for pngs which don't seem to actually be changing?

**Comment by Mr-Milk** [comment]
Sure the label can be rotated.

I'm not sure how to remove the updated picture, the notebook store image in base64, if I rerun the notebook the image encoding will be different even though the image look the same. Do you have any idea how to do it?

**Review by flying-sheep — CHANGES_REQUESTED** [review]
See above

**Comment by Mr-Milk** [comment]
<p>I've change the labels on the right side, do you mean rotate these labels or the axis labels for numbers?</p>

---

 <a href='https://app.reviewnb.com/scverse/scanpy-tutorials/pull/101/discussion/#comment-2076703996'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by flying-sheep** [comment]
Ah, maybe he meant the side labels, which were actually unreadable before. I referred to the bottom labels, which are readable, but take up more space than necessary. But not necessary.

**Review by flying-sheep — APPROVED** [review]

**Pull request merged**
